# Site settings
title: mirrexagon.com
email: mirrexagon@tuta.io
description: >
    Mirrexagon's personal website
baseurl: ""
url: "https://mirrexagon.com"
github_username: mirrexagon

# Build settings
markdown: kramdown
