# Site settings
title: mirrexagon.com
email: mirrexagon@mirrexagon.com
description: >
    Mirrexagon's personal website
baseurl: ""
url: "http://www.mirrexagon.com"
github_username: mirrexagon

# Build settings
markdown: kramdown
